-- Seed — entity registry (Phase 5 SP1, recursive interest picker)
--
-- Source of truth: interest_picker.html's DATA const (the approved prototype's full
-- seed dataset). Rows are LIFTED (not re-authored) — every entity_id is the prototype's
-- path-derived chip id: idBase + '/' + slug(label), where slug = lowercase, non-alnum -> '-',
-- trimmed. entity_slug == entity_id. entity_parent_slug is the seeding set-id (the
-- listEntities scope). Only ENTITY nodes (those with a `kind`) are seeded — pure TOPIC
-- nodes live in the `interests` taxonomy (supabase/seed/interests.sql), not here.
--
-- Depends on migration 0007 (entities table + entity_kind enum). Run AFTER migrations.
-- IDEMPOTENT: `on conflict (entity_id) do nothing` — safe to re-run. 248 rows
-- across 6 categories. Labels with apostrophes (A''ja Wilson) are
-- SQL-escaped; tickers with dots (BRK.B, ENR.DE) are plain text.

-- ── AI (14) ──────────────────────────────────────────────────────
insert into entities (entity_id, entity_slug, entity_label, entity_kind, entity_ticker, entity_parent_slug, entity_search_query)
values
  ('ai/foundation-models-llms/labs-models/openai', 'ai/foundation-models-llms/labs-models/openai', 'OpenAI', 'org', null, 'ai/foundation-models-llms', 'OpenAI'),
  ('ai/foundation-models-llms/labs-models/anthropic', 'ai/foundation-models-llms/labs-models/anthropic', 'Anthropic', 'org', null, 'ai/foundation-models-llms', 'Anthropic'),
  ('ai/foundation-models-llms/labs-models/google-deepmind', 'ai/foundation-models-llms/labs-models/google-deepmind', 'Google DeepMind', 'org', null, 'ai/foundation-models-llms', 'Google DeepMind'),
  ('ai/foundation-models-llms/labs-models/meta-ai', 'ai/foundation-models-llms/labs-models/meta-ai', 'Meta AI', 'org', null, 'ai/foundation-models-llms', 'Meta AI'),
  ('ai/foundation-models-llms/labs-models/mistral', 'ai/foundation-models-llms/labs-models/mistral', 'Mistral', 'org', null, 'ai/foundation-models-llms', 'Mistral'),
  ('ai/foundation-models-llms/labs-models/xai', 'ai/foundation-models-llms/labs-models/xai', 'xAI', 'org', null, 'ai/foundation-models-llms', 'xAI'),
  ('ai/foundation-models-llms/labs-models/deepseek', 'ai/foundation-models-llms/labs-models/deepseek', 'DeepSeek', 'org', null, 'ai/foundation-models-llms', 'DeepSeek'),
  ('ai/ai-hardware-compute/companies-topics/nvidia', 'ai/ai-hardware-compute/companies-topics/nvidia', 'Nvidia', 'company', 'NVDA', 'ai/ai-hardware-compute', 'Nvidia NVDA'),
  ('ai/ai-hardware-compute/companies-topics/amd', 'ai/ai-hardware-compute/companies-topics/amd', 'AMD', 'company', 'AMD', 'ai/ai-hardware-compute', 'AMD AMD'),
  ('ai/ai-hardware-compute/companies-topics/broadcom', 'ai/ai-hardware-compute/companies-topics/broadcom', 'Broadcom', 'company', 'AVGO', 'ai/ai-hardware-compute', 'Broadcom AVGO'),
  ('ai/ai-hardware-compute/companies-topics/tsmc', 'ai/ai-hardware-compute/companies-topics/tsmc', 'TSMC', 'company', 'TSM', 'ai/ai-hardware-compute', 'TSMC TSM'),
  ('ai/robotics-embodied-ai/topics-makers/tesla-optimus', 'ai/robotics-embodied-ai/topics-makers/tesla-optimus', 'Tesla Optimus', 'product', null, 'ai/robotics-embodied-ai', 'Tesla Optimus'),
  ('ai/robotics-embodied-ai/topics-makers/figure', 'ai/robotics-embodied-ai/topics-makers/figure', 'Figure', 'company', null, 'ai/robotics-embodied-ai', 'Figure'),
  ('ai/robotics-embodied-ai/topics-makers/waymo', 'ai/robotics-embodied-ai/topics-makers/waymo', 'Waymo', 'company', null, 'ai/robotics-embodied-ai', 'Waymo')
on conflict (entity_id) do nothing;

-- ── Geopolitics (8) ──────────────────────────────────────────────────────
insert into entities (entity_id, entity_slug, entity_label, entity_kind, entity_ticker, entity_parent_slug, entity_search_query)
values
  ('geopolitics/armed-conflict-war/conflicts/ukraine-russia', 'geopolitics/armed-conflict-war/conflicts/ukraine-russia', 'Ukraine–Russia', 'conflict', null, 'geopolitics/armed-conflict-war', 'Ukraine–Russia'),
  ('geopolitics/armed-conflict-war/conflicts/middle-east', 'geopolitics/armed-conflict-war/conflicts/middle-east', 'Middle East', 'conflict', null, 'geopolitics/armed-conflict-war', 'Middle East'),
  ('geopolitics/armed-conflict-war/conflicts/african-conflicts', 'geopolitics/armed-conflict-war/conflicts/african-conflicts', 'African conflicts', 'conflict', null, 'geopolitics/armed-conflict-war', 'African conflicts'),
  ('geopolitics/armed-conflict-war/conflicts/asia-pacific-tensions', 'geopolitics/armed-conflict-war/conflicts/asia-pacific-tensions', 'Asia-Pacific tensions', 'conflict', null, 'geopolitics/armed-conflict-war', 'Asia-Pacific tensions'),
  ('geopolitics/alliances-blocs/organizations/nato', 'geopolitics/alliances-blocs/organizations/nato', 'NATO', 'org', null, 'geopolitics/alliances-blocs', 'NATO'),
  ('geopolitics/alliances-blocs/organizations/european-union', 'geopolitics/alliances-blocs/organizations/european-union', 'European Union', 'org', null, 'geopolitics/alliances-blocs', 'European Union'),
  ('geopolitics/alliances-blocs/organizations/brics', 'geopolitics/alliances-blocs/organizations/brics', 'BRICS', 'org', null, 'geopolitics/alliances-blocs', 'BRICS'),
  ('geopolitics/alliances-blocs/organizations/asean', 'geopolitics/alliances-blocs/organizations/asean', 'ASEAN', 'org', null, 'geopolitics/alliances-blocs', 'ASEAN')
on conflict (entity_id) do nothing;

-- ── Business (38) ──────────────────────────────────────────────────────
insert into entities (entity_id, entity_slug, entity_label, entity_kind, entity_ticker, entity_parent_slug, entity_search_query)
values
  ('business/corporate-news/what-to-track/earnings/companies-to-track/apple', 'business/corporate-news/what-to-track/earnings/companies-to-track/apple', 'Apple', 'company', 'AAPL', 'business/corporate-news/what-to-track/earnings', 'Apple AAPL'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/microsoft', 'business/corporate-news/what-to-track/earnings/companies-to-track/microsoft', 'Microsoft', 'company', 'MSFT', 'business/corporate-news/what-to-track/earnings', 'Microsoft MSFT'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/nvidia', 'business/corporate-news/what-to-track/earnings/companies-to-track/nvidia', 'Nvidia', 'company', 'NVDA', 'business/corporate-news/what-to-track/earnings', 'Nvidia NVDA'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/amazon', 'business/corporate-news/what-to-track/earnings/companies-to-track/amazon', 'Amazon', 'company', 'AMZN', 'business/corporate-news/what-to-track/earnings', 'Amazon AMZN'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/alphabet', 'business/corporate-news/what-to-track/earnings/companies-to-track/alphabet', 'Alphabet', 'company', 'GOOGL', 'business/corporate-news/what-to-track/earnings', 'Alphabet GOOGL'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/meta', 'business/corporate-news/what-to-track/earnings/companies-to-track/meta', 'Meta', 'company', 'META', 'business/corporate-news/what-to-track/earnings', 'Meta META'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/tesla', 'business/corporate-news/what-to-track/earnings/companies-to-track/tesla', 'Tesla', 'company', 'TSLA', 'business/corporate-news/what-to-track/earnings', 'Tesla TSLA'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/eli-lilly', 'business/corporate-news/what-to-track/earnings/companies-to-track/eli-lilly', 'Eli Lilly', 'company', 'LLY', 'business/corporate-news/what-to-track/earnings', 'Eli Lilly LLY'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/berkshire-hathaway', 'business/corporate-news/what-to-track/earnings/companies-to-track/berkshire-hathaway', 'Berkshire Hathaway', 'company', 'BRK.B', 'business/corporate-news/what-to-track/earnings', 'Berkshire Hathaway BRK.B'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/jpmorgan', 'business/corporate-news/what-to-track/earnings/companies-to-track/jpmorgan', 'JPMorgan', 'company', 'JPM', 'business/corporate-news/what-to-track/earnings', 'JPMorgan JPM'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/visa', 'business/corporate-news/what-to-track/earnings/companies-to-track/visa', 'Visa', 'company', 'V', 'business/corporate-news/what-to-track/earnings', 'Visa V'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/walmart', 'business/corporate-news/what-to-track/earnings/companies-to-track/walmart', 'Walmart', 'company', 'WMT', 'business/corporate-news/what-to-track/earnings', 'Walmart WMT'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/broadcom', 'business/corporate-news/what-to-track/earnings/companies-to-track/broadcom', 'Broadcom', 'company', 'AVGO', 'business/corporate-news/what-to-track/earnings', 'Broadcom AVGO'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/unitedhealth', 'business/corporate-news/what-to-track/earnings/companies-to-track/unitedhealth', 'UnitedHealth', 'company', 'UNH', 'business/corporate-news/what-to-track/earnings', 'UnitedHealth UNH'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/exxon', 'business/corporate-news/what-to-track/earnings/companies-to-track/exxon', 'Exxon', 'company', 'XOM', 'business/corporate-news/what-to-track/earnings', 'Exxon XOM'),
  ('business/corporate-news/what-to-track/earnings/companies-to-track/costco', 'business/corporate-news/what-to-track/earnings/companies-to-track/costco', 'Costco', 'company', 'COST', 'business/corporate-news/what-to-track/earnings', 'Costco COST'),
  ('business/energy-commodities/sectors/oil-gas/majors/exxonmobil', 'business/energy-commodities/sectors/oil-gas/majors/exxonmobil', 'ExxonMobil', 'company', 'XOM', 'business/energy-commodities/sectors/oil-gas', 'ExxonMobil XOM'),
  ('business/energy-commodities/sectors/oil-gas/majors/chevron', 'business/energy-commodities/sectors/oil-gas/majors/chevron', 'Chevron', 'company', 'CVX', 'business/energy-commodities/sectors/oil-gas', 'Chevron CVX'),
  ('business/energy-commodities/sectors/oil-gas/majors/shell', 'business/energy-commodities/sectors/oil-gas/majors/shell', 'Shell', 'company', 'SHEL', 'business/energy-commodities/sectors/oil-gas', 'Shell SHEL'),
  ('business/energy-commodities/sectors/oil-gas/majors/bp', 'business/energy-commodities/sectors/oil-gas/majors/bp', 'BP', 'company', 'BP', 'business/energy-commodities/sectors/oil-gas', 'BP BP'),
  ('business/energy-commodities/sectors/oil-gas/majors/conocophillips', 'business/energy-commodities/sectors/oil-gas/majors/conocophillips', 'ConocoPhillips', 'company', 'COP', 'business/energy-commodities/sectors/oil-gas', 'ConocoPhillips COP'),
  ('business/energy-commodities/sectors/oil-gas/majors/totalenergies', 'business/energy-commodities/sectors/oil-gas/majors/totalenergies', 'TotalEnergies', 'company', 'TTE', 'business/energy-commodities/sectors/oil-gas', 'TotalEnergies TTE'),
  ('business/energy-commodities/sectors/oil-gas/midstream-pipelines/kinder-morgan', 'business/energy-commodities/sectors/oil-gas/midstream-pipelines/kinder-morgan', 'Kinder Morgan', 'company', 'KMI', 'business/energy-commodities/sectors/oil-gas', 'Kinder Morgan KMI'),
  ('business/energy-commodities/sectors/oil-gas/midstream-pipelines/enbridge', 'business/energy-commodities/sectors/oil-gas/midstream-pipelines/enbridge', 'Enbridge', 'company', 'ENB', 'business/energy-commodities/sectors/oil-gas', 'Enbridge ENB'),
  ('business/energy-commodities/sectors/oil-gas/midstream-pipelines/williams-companies', 'business/energy-commodities/sectors/oil-gas/midstream-pipelines/williams-companies', 'Williams Companies', 'company', 'WMB', 'business/energy-commodities/sectors/oil-gas', 'Williams Companies WMB'),
  ('business/energy-commodities/sectors/oil-gas/midstream-pipelines/energy-transfer', 'business/energy-commodities/sectors/oil-gas/midstream-pipelines/energy-transfer', 'Energy Transfer', 'company', 'ET', 'business/energy-commodities/sectors/oil-gas', 'Energy Transfer ET'),
  ('business/energy-commodities/sectors/oil-gas/midstream-pipelines/tc-energy', 'business/energy-commodities/sectors/oil-gas/midstream-pipelines/tc-energy', 'TC Energy', 'company', 'TRP', 'business/energy-commodities/sectors/oil-gas', 'TC Energy TRP'),
  ('business/energy-commodities/sectors/oil-gas/midstream-pipelines/oneok', 'business/energy-commodities/sectors/oil-gas/midstream-pipelines/oneok', 'ONEOK', 'company', 'OKE', 'business/energy-commodities/sectors/oil-gas', 'ONEOK OKE'),
  ('business/energy-commodities/sectors/oil-gas/equipment-turbines-services/ge-vernova', 'business/energy-commodities/sectors/oil-gas/equipment-turbines-services/ge-vernova', 'GE Vernova', 'company', 'GEV', 'business/energy-commodities/sectors/oil-gas', 'GE Vernova GEV'),
  ('business/energy-commodities/sectors/oil-gas/equipment-turbines-services/siemens-energy', 'business/energy-commodities/sectors/oil-gas/equipment-turbines-services/siemens-energy', 'Siemens Energy', 'company', 'ENR.DE', 'business/energy-commodities/sectors/oil-gas', 'Siemens Energy ENR.DE'),
  ('business/energy-commodities/sectors/oil-gas/equipment-turbines-services/baker-hughes', 'business/energy-commodities/sectors/oil-gas/equipment-turbines-services/baker-hughes', 'Baker Hughes', 'company', 'BKR', 'business/energy-commodities/sectors/oil-gas', 'Baker Hughes BKR'),
  ('business/energy-commodities/sectors/oil-gas/equipment-turbines-services/slb-schlumberger', 'business/energy-commodities/sectors/oil-gas/equipment-turbines-services/slb-schlumberger', 'SLB (Schlumberger)', 'company', 'SLB', 'business/energy-commodities/sectors/oil-gas', 'SLB (Schlumberger) SLB'),
  ('business/energy-commodities/sectors/oil-gas/equipment-turbines-services/halliburton', 'business/energy-commodities/sectors/oil-gas/equipment-turbines-services/halliburton', 'Halliburton', 'company', 'HAL', 'business/energy-commodities/sectors/oil-gas', 'Halliburton HAL'),
  ('business/energy-commodities/sectors/oil-gas/equipment-turbines-services/nov-inc', 'business/energy-commodities/sectors/oil-gas/equipment-turbines-services/nov-inc', 'NOV Inc.', 'company', 'NOV', 'business/energy-commodities/sectors/oil-gas', 'NOV Inc. NOV'),
  ('business/crypto-fintech/assets-topics/bitcoin', 'business/crypto-fintech/assets-topics/bitcoin', 'Bitcoin', 'asset', null, 'business/crypto-fintech', 'Bitcoin'),
  ('business/crypto-fintech/assets-topics/ethereum', 'business/crypto-fintech/assets-topics/ethereum', 'Ethereum', 'asset', null, 'business/crypto-fintech', 'Ethereum'),
  ('business/crypto-fintech/assets-topics/solana', 'business/crypto-fintech/assets-topics/solana', 'Solana', 'asset', null, 'business/crypto-fintech', 'Solana'),
  ('business/crypto-fintech/assets-topics/coinbase', 'business/crypto-fintech/assets-topics/coinbase', 'Coinbase', 'company', 'COIN', 'business/crypto-fintech', 'Coinbase COIN')
on conflict (entity_id) do nothing;

-- ── Tech (16) ──────────────────────────────────────────────────────
insert into entities (entity_id, entity_slug, entity_label, entity_kind, entity_ticker, entity_parent_slug, entity_search_query)
values
  ('tech/social-media-platforms/platforms/x', 'tech/social-media-platforms/platforms/x', 'X', 'company', null, 'tech/social-media-platforms', 'X'),
  ('tech/social-media-platforms/platforms/meta', 'tech/social-media-platforms/platforms/meta', 'Meta', 'company', null, 'tech/social-media-platforms', 'Meta'),
  ('tech/social-media-platforms/platforms/tiktok', 'tech/social-media-platforms/platforms/tiktok', 'TikTok', 'company', null, 'tech/social-media-platforms', 'TikTok'),
  ('tech/social-media-platforms/platforms/youtube', 'tech/social-media-platforms/platforms/youtube', 'YouTube', 'company', null, 'tech/social-media-platforms', 'YouTube'),
  ('tech/social-media-platforms/platforms/reddit', 'tech/social-media-platforms/platforms/reddit', 'Reddit', 'company', null, 'tech/social-media-platforms', 'Reddit'),
  ('tech/semiconductors-chips/companies/nvidia', 'tech/semiconductors-chips/companies/nvidia', 'Nvidia', 'company', 'NVDA', 'tech/semiconductors-chips', 'Nvidia NVDA'),
  ('tech/semiconductors-chips/companies/tsmc', 'tech/semiconductors-chips/companies/tsmc', 'TSMC', 'company', 'TSM', 'tech/semiconductors-chips', 'TSMC TSM'),
  ('tech/semiconductors-chips/companies/intel', 'tech/semiconductors-chips/companies/intel', 'Intel', 'company', 'INTC', 'tech/semiconductors-chips', 'Intel INTC'),
  ('tech/semiconductors-chips/companies/amd', 'tech/semiconductors-chips/companies/amd', 'AMD', 'company', 'AMD', 'tech/semiconductors-chips', 'AMD AMD'),
  ('tech/semiconductors-chips/companies/asml', 'tech/semiconductors-chips/companies/asml', 'ASML', 'company', 'ASML', 'tech/semiconductors-chips', 'ASML ASML'),
  ('tech/space-aerospace/players/spacex', 'tech/space-aerospace/players/spacex', 'SpaceX', 'company', null, 'tech/space-aerospace', 'SpaceX'),
  ('tech/space-aerospace/players/nasa', 'tech/space-aerospace/players/nasa', 'NASA', 'org', null, 'tech/space-aerospace', 'NASA'),
  ('tech/space-aerospace/players/blue-origin', 'tech/space-aerospace/players/blue-origin', 'Blue Origin', 'company', null, 'tech/space-aerospace', 'Blue Origin'),
  ('tech/space-aerospace/players/rocket-lab', 'tech/space-aerospace/players/rocket-lab', 'Rocket Lab', 'company', 'RKLB', 'tech/space-aerospace', 'Rocket Lab RKLB'),
  ('tech/gaming/topics-studios/nintendo', 'tech/gaming/topics-studios/nintendo', 'Nintendo', 'company', null, 'tech/gaming', 'Nintendo'),
  ('tech/gaming/topics-studios/sony', 'tech/gaming/topics-studios/sony', 'Sony', 'company', null, 'tech/gaming', 'Sony')
on conflict (entity_id) do nothing;

-- ── Sport (121) ──────────────────────────────────────────────────────
insert into entities (entity_id, entity_slug, entity_label, entity_kind, entity_ticker, entity_parent_slug, entity_search_query)
values
  ('sport/american-football/leagues/nfl', 'sport/american-football/leagues/nfl', 'NFL', 'league', null, 'sport/american-football', 'NFL'),
  ('sport/american-football/leagues/nfl/teams-you-follow/kansas-city-chiefs', 'sport/american-football/leagues/nfl/teams-you-follow/kansas-city-chiefs', 'Kansas City Chiefs', 'team', null, 'sport/american-football/leagues/nfl', 'Kansas City Chiefs'),
  ('sport/american-football/leagues/nfl/teams-you-follow/philadelphia-eagles', 'sport/american-football/leagues/nfl/teams-you-follow/philadelphia-eagles', 'Philadelphia Eagles', 'team', null, 'sport/american-football/leagues/nfl', 'Philadelphia Eagles'),
  ('sport/american-football/leagues/nfl/teams-you-follow/san-francisco-49ers', 'sport/american-football/leagues/nfl/teams-you-follow/san-francisco-49ers', 'San Francisco 49ers', 'team', null, 'sport/american-football/leagues/nfl', 'San Francisco 49ers'),
  ('sport/american-football/leagues/nfl/teams-you-follow/dallas-cowboys', 'sport/american-football/leagues/nfl/teams-you-follow/dallas-cowboys', 'Dallas Cowboys', 'team', null, 'sport/american-football/leagues/nfl', 'Dallas Cowboys'),
  ('sport/american-football/leagues/nfl/teams-you-follow/buffalo-bills', 'sport/american-football/leagues/nfl/teams-you-follow/buffalo-bills', 'Buffalo Bills', 'team', null, 'sport/american-football/leagues/nfl', 'Buffalo Bills'),
  ('sport/american-football/leagues/nfl/teams-you-follow/baltimore-ravens', 'sport/american-football/leagues/nfl/teams-you-follow/baltimore-ravens', 'Baltimore Ravens', 'team', null, 'sport/american-football/leagues/nfl', 'Baltimore Ravens'),
  ('sport/american-football/leagues/nfl/teams-you-follow/detroit-lions', 'sport/american-football/leagues/nfl/teams-you-follow/detroit-lions', 'Detroit Lions', 'team', null, 'sport/american-football/leagues/nfl', 'Detroit Lions'),
  ('sport/american-football/leagues/nfl/teams-you-follow/green-bay-packers', 'sport/american-football/leagues/nfl/teams-you-follow/green-bay-packers', 'Green Bay Packers', 'team', null, 'sport/american-football/leagues/nfl', 'Green Bay Packers'),
  ('sport/american-football/leagues/nfl/teams-you-follow/miami-dolphins', 'sport/american-football/leagues/nfl/teams-you-follow/miami-dolphins', 'Miami Dolphins', 'team', null, 'sport/american-football/leagues/nfl', 'Miami Dolphins'),
  ('sport/american-football/leagues/nfl/teams-you-follow/pittsburgh-steelers', 'sport/american-football/leagues/nfl/teams-you-follow/pittsburgh-steelers', 'Pittsburgh Steelers', 'team', null, 'sport/american-football/leagues/nfl', 'Pittsburgh Steelers'),
  ('sport/american-football/leagues/nfl/teams-you-follow/cincinnati-bengals', 'sport/american-football/leagues/nfl/teams-you-follow/cincinnati-bengals', 'Cincinnati Bengals', 'team', null, 'sport/american-football/leagues/nfl', 'Cincinnati Bengals'),
  ('sport/american-football/leagues/nfl/teams-you-follow/minnesota-vikings', 'sport/american-football/leagues/nfl/teams-you-follow/minnesota-vikings', 'Minnesota Vikings', 'team', null, 'sport/american-football/leagues/nfl', 'Minnesota Vikings'),
  ('sport/american-football/leagues/nfl/teams-you-follow/houston-texans', 'sport/american-football/leagues/nfl/teams-you-follow/houston-texans', 'Houston Texans', 'team', null, 'sport/american-football/leagues/nfl', 'Houston Texans'),
  ('sport/american-football/leagues/nfl/teams-you-follow/los-angeles-rams', 'sport/american-football/leagues/nfl/teams-you-follow/los-angeles-rams', 'Los Angeles Rams', 'team', null, 'sport/american-football/leagues/nfl', 'Los Angeles Rams'),
  ('sport/american-football/leagues/nfl/teams-you-follow/new-york-jets', 'sport/american-football/leagues/nfl/teams-you-follow/new-york-jets', 'New York Jets', 'team', null, 'sport/american-football/leagues/nfl', 'New York Jets'),
  ('sport/american-football/leagues/nfl/teams-you-follow/seattle-seahawks', 'sport/american-football/leagues/nfl/teams-you-follow/seattle-seahawks', 'Seattle Seahawks', 'team', null, 'sport/american-football/leagues/nfl', 'Seattle Seahawks'),
  ('sport/american-football/leagues/nfl/people-to-follow/patrick-mahomes', 'sport/american-football/leagues/nfl/people-to-follow/patrick-mahomes', 'Patrick Mahomes', 'person', null, 'sport/american-football/leagues/nfl', 'Patrick Mahomes'),
  ('sport/american-football/leagues/nfl/people-to-follow/josh-allen', 'sport/american-football/leagues/nfl/people-to-follow/josh-allen', 'Josh Allen', 'person', null, 'sport/american-football/leagues/nfl', 'Josh Allen'),
  ('sport/american-football/leagues/nfl/people-to-follow/lamar-jackson', 'sport/american-football/leagues/nfl/people-to-follow/lamar-jackson', 'Lamar Jackson', 'person', null, 'sport/american-football/leagues/nfl', 'Lamar Jackson'),
  ('sport/american-football/leagues/nfl/people-to-follow/jalen-hurts', 'sport/american-football/leagues/nfl/people-to-follow/jalen-hurts', 'Jalen Hurts', 'person', null, 'sport/american-football/leagues/nfl', 'Jalen Hurts'),
  ('sport/american-football/leagues/nfl/people-to-follow/andy-reid', 'sport/american-football/leagues/nfl/people-to-follow/andy-reid', 'Andy Reid', 'person', null, 'sport/american-football/leagues/nfl', 'Andy Reid'),
  ('sport/american-football/leagues/nfl/people-to-follow/saquon-barkley', 'sport/american-football/leagues/nfl/people-to-follow/saquon-barkley', 'Saquon Barkley', 'person', null, 'sport/american-football/leagues/nfl', 'Saquon Barkley'),
  ('sport/american-football/leagues/college-football', 'sport/american-football/leagues/college-football', 'College football', 'league', null, 'sport/american-football', 'College football'),
  ('sport/american-football/leagues/college-football/teams-you-follow/georgia', 'sport/american-football/leagues/college-football/teams-you-follow/georgia', 'Georgia', 'team', null, 'sport/american-football/leagues/college-football', 'Georgia'),
  ('sport/american-football/leagues/college-football/teams-you-follow/michigan', 'sport/american-football/leagues/college-football/teams-you-follow/michigan', 'Michigan', 'team', null, 'sport/american-football/leagues/college-football', 'Michigan'),
  ('sport/american-football/leagues/college-football/teams-you-follow/ohio-state', 'sport/american-football/leagues/college-football/teams-you-follow/ohio-state', 'Ohio State', 'team', null, 'sport/american-football/leagues/college-football', 'Ohio State'),
  ('sport/american-football/leagues/college-football/teams-you-follow/alabama', 'sport/american-football/leagues/college-football/teams-you-follow/alabama', 'Alabama', 'team', null, 'sport/american-football/leagues/college-football', 'Alabama'),
  ('sport/american-football/leagues/college-football/teams-you-follow/texas', 'sport/american-football/leagues/college-football/teams-you-follow/texas', 'Texas', 'team', null, 'sport/american-football/leagues/college-football', 'Texas'),
  ('sport/american-football/leagues/college-football/teams-you-follow/oregon', 'sport/american-football/leagues/college-football/teams-you-follow/oregon', 'Oregon', 'team', null, 'sport/american-football/leagues/college-football', 'Oregon'),
  ('sport/american-football/leagues/college-football/teams-you-follow/notre-dame', 'sport/american-football/leagues/college-football/teams-you-follow/notre-dame', 'Notre Dame', 'team', null, 'sport/american-football/leagues/college-football', 'Notre Dame'),
  ('sport/american-football/leagues/college-football/teams-you-follow/usc', 'sport/american-football/leagues/college-football/teams-you-follow/usc', 'USC', 'team', null, 'sport/american-football/leagues/college-football', 'USC'),
  ('sport/american-football/leagues/college-football/teams-you-follow/penn-state', 'sport/american-football/leagues/college-football/teams-you-follow/penn-state', 'Penn State', 'team', null, 'sport/american-football/leagues/college-football', 'Penn State'),
  ('sport/american-football/leagues/college-football/teams-you-follow/lsu', 'sport/american-football/leagues/college-football/teams-you-follow/lsu', 'LSU', 'team', null, 'sport/american-football/leagues/college-football', 'LSU'),
  ('sport/american-football/leagues/college-football/teams-you-follow/tennessee', 'sport/american-football/leagues/college-football/teams-you-follow/tennessee', 'Tennessee', 'team', null, 'sport/american-football/leagues/college-football', 'Tennessee'),
  ('sport/american-football/leagues/college-football/teams-you-follow/florida-state', 'sport/american-football/leagues/college-football/teams-you-follow/florida-state', 'Florida State', 'team', null, 'sport/american-football/leagues/college-football', 'Florida State'),
  ('sport/american-football/leagues/college-football/teams-you-follow/oklahoma', 'sport/american-football/leagues/college-football/teams-you-follow/oklahoma', 'Oklahoma', 'team', null, 'sport/american-football/leagues/college-football', 'Oklahoma'),
  ('sport/american-football/leagues/college-football/teams-you-follow/clemson', 'sport/american-football/leagues/college-football/teams-you-follow/clemson', 'Clemson', 'team', null, 'sport/american-football/leagues/college-football', 'Clemson'),
  ('sport/american-football/leagues/college-football/people-to-follow/kirby-smart', 'sport/american-football/leagues/college-football/people-to-follow/kirby-smart', 'Kirby Smart', 'person', null, 'sport/american-football/leagues/college-football', 'Kirby Smart'),
  ('sport/american-football/leagues/college-football/people-to-follow/ryan-day', 'sport/american-football/leagues/college-football/people-to-follow/ryan-day', 'Ryan Day', 'person', null, 'sport/american-football/leagues/college-football', 'Ryan Day'),
  ('sport/american-football/leagues/college-football/people-to-follow/dabo-swinney', 'sport/american-football/leagues/college-football/people-to-follow/dabo-swinney', 'Dabo Swinney', 'person', null, 'sport/american-football/leagues/college-football', 'Dabo Swinney'),
  ('sport/american-football/leagues/college-football/people-to-follow/deion-sanders', 'sport/american-football/leagues/college-football/people-to-follow/deion-sanders', 'Deion Sanders', 'person', null, 'sport/american-football/leagues/college-football', 'Deion Sanders'),
  ('sport/basketball/leagues/nba', 'sport/basketball/leagues/nba', 'NBA', 'league', null, 'sport/basketball', 'NBA'),
  ('sport/basketball/leagues/nba/teams-you-follow/boston-celtics', 'sport/basketball/leagues/nba/teams-you-follow/boston-celtics', 'Boston Celtics', 'team', null, 'sport/basketball/leagues/nba', 'Boston Celtics'),
  ('sport/basketball/leagues/nba/teams-you-follow/los-angeles-lakers', 'sport/basketball/leagues/nba/teams-you-follow/los-angeles-lakers', 'Los Angeles Lakers', 'team', null, 'sport/basketball/leagues/nba', 'Los Angeles Lakers'),
  ('sport/basketball/leagues/nba/teams-you-follow/golden-state-warriors', 'sport/basketball/leagues/nba/teams-you-follow/golden-state-warriors', 'Golden State Warriors', 'team', null, 'sport/basketball/leagues/nba', 'Golden State Warriors'),
  ('sport/basketball/leagues/nba/teams-you-follow/denver-nuggets', 'sport/basketball/leagues/nba/teams-you-follow/denver-nuggets', 'Denver Nuggets', 'team', null, 'sport/basketball/leagues/nba', 'Denver Nuggets'),
  ('sport/basketball/leagues/nba/teams-you-follow/milwaukee-bucks', 'sport/basketball/leagues/nba/teams-you-follow/milwaukee-bucks', 'Milwaukee Bucks', 'team', null, 'sport/basketball/leagues/nba', 'Milwaukee Bucks'),
  ('sport/basketball/leagues/nba/teams-you-follow/new-york-knicks', 'sport/basketball/leagues/nba/teams-you-follow/new-york-knicks', 'New York Knicks', 'team', null, 'sport/basketball/leagues/nba', 'New York Knicks'),
  ('sport/basketball/leagues/nba/teams-you-follow/dallas-mavericks', 'sport/basketball/leagues/nba/teams-you-follow/dallas-mavericks', 'Dallas Mavericks', 'team', null, 'sport/basketball/leagues/nba', 'Dallas Mavericks'),
  ('sport/basketball/leagues/nba/teams-you-follow/oklahoma-city-thunder', 'sport/basketball/leagues/nba/teams-you-follow/oklahoma-city-thunder', 'Oklahoma City Thunder', 'team', null, 'sport/basketball/leagues/nba', 'Oklahoma City Thunder'),
  ('sport/basketball/leagues/nba/teams-you-follow/miami-heat', 'sport/basketball/leagues/nba/teams-you-follow/miami-heat', 'Miami Heat', 'team', null, 'sport/basketball/leagues/nba', 'Miami Heat'),
  ('sport/basketball/leagues/nba/teams-you-follow/philadelphia-76ers', 'sport/basketball/leagues/nba/teams-you-follow/philadelphia-76ers', 'Philadelphia 76ers', 'team', null, 'sport/basketball/leagues/nba', 'Philadelphia 76ers'),
  ('sport/basketball/leagues/nba/teams-you-follow/phoenix-suns', 'sport/basketball/leagues/nba/teams-you-follow/phoenix-suns', 'Phoenix Suns', 'team', null, 'sport/basketball/leagues/nba', 'Phoenix Suns'),
  ('sport/basketball/leagues/nba/teams-you-follow/minnesota-timberwolves', 'sport/basketball/leagues/nba/teams-you-follow/minnesota-timberwolves', 'Minnesota Timberwolves', 'team', null, 'sport/basketball/leagues/nba', 'Minnesota Timberwolves'),
  ('sport/basketball/leagues/nba/people-to-follow/lebron-james', 'sport/basketball/leagues/nba/people-to-follow/lebron-james', 'LeBron James', 'person', null, 'sport/basketball/leagues/nba', 'LeBron James'),
  ('sport/basketball/leagues/nba/people-to-follow/stephen-curry', 'sport/basketball/leagues/nba/people-to-follow/stephen-curry', 'Stephen Curry', 'person', null, 'sport/basketball/leagues/nba', 'Stephen Curry'),
  ('sport/basketball/leagues/nba/people-to-follow/nikola-jokic', 'sport/basketball/leagues/nba/people-to-follow/nikola-jokic', 'Nikola Jokic', 'person', null, 'sport/basketball/leagues/nba', 'Nikola Jokic'),
  ('sport/basketball/leagues/nba/people-to-follow/luka-doncic', 'sport/basketball/leagues/nba/people-to-follow/luka-doncic', 'Luka Doncic', 'person', null, 'sport/basketball/leagues/nba', 'Luka Doncic'),
  ('sport/basketball/leagues/nba/people-to-follow/giannis-antetokounmpo', 'sport/basketball/leagues/nba/people-to-follow/giannis-antetokounmpo', 'Giannis Antetokounmpo', 'person', null, 'sport/basketball/leagues/nba', 'Giannis Antetokounmpo'),
  ('sport/basketball/leagues/wnba', 'sport/basketball/leagues/wnba', 'WNBA', 'league', null, 'sport/basketball', 'WNBA'),
  ('sport/basketball/leagues/wnba/teams-you-follow/las-vegas-aces', 'sport/basketball/leagues/wnba/teams-you-follow/las-vegas-aces', 'Las Vegas Aces', 'team', null, 'sport/basketball/leagues/wnba', 'Las Vegas Aces'),
  ('sport/basketball/leagues/wnba/teams-you-follow/new-york-liberty', 'sport/basketball/leagues/wnba/teams-you-follow/new-york-liberty', 'New York Liberty', 'team', null, 'sport/basketball/leagues/wnba', 'New York Liberty'),
  ('sport/basketball/leagues/wnba/teams-you-follow/indiana-fever', 'sport/basketball/leagues/wnba/teams-you-follow/indiana-fever', 'Indiana Fever', 'team', null, 'sport/basketball/leagues/wnba', 'Indiana Fever'),
  ('sport/basketball/leagues/wnba/teams-you-follow/connecticut-sun', 'sport/basketball/leagues/wnba/teams-you-follow/connecticut-sun', 'Connecticut Sun', 'team', null, 'sport/basketball/leagues/wnba', 'Connecticut Sun'),
  ('sport/basketball/leagues/wnba/people-to-follow/caitlin-clark', 'sport/basketball/leagues/wnba/people-to-follow/caitlin-clark', 'Caitlin Clark', 'person', null, 'sport/basketball/leagues/wnba', 'Caitlin Clark'),
  ('sport/basketball/leagues/wnba/people-to-follow/a-ja-wilson', 'sport/basketball/leagues/wnba/people-to-follow/a-ja-wilson', 'A''ja Wilson', 'person', null, 'sport/basketball/leagues/wnba', 'A''ja Wilson'),
  ('sport/basketball/leagues/wnba/people-to-follow/breanna-stewart', 'sport/basketball/leagues/wnba/people-to-follow/breanna-stewart', 'Breanna Stewart', 'person', null, 'sport/basketball/leagues/wnba', 'Breanna Stewart'),
  ('sport/basketball/leagues/wnba/people-to-follow/angel-reese', 'sport/basketball/leagues/wnba/people-to-follow/angel-reese', 'Angel Reese', 'person', null, 'sport/basketball/leagues/wnba', 'Angel Reese'),
  ('sport/baseball/leagues/mlb', 'sport/baseball/leagues/mlb', 'MLB', 'league', null, 'sport/baseball', 'MLB'),
  ('sport/baseball/leagues/mlb/teams-you-follow/los-angeles-dodgers', 'sport/baseball/leagues/mlb/teams-you-follow/los-angeles-dodgers', 'Los Angeles Dodgers', 'team', null, 'sport/baseball/leagues/mlb', 'Los Angeles Dodgers'),
  ('sport/baseball/leagues/mlb/teams-you-follow/new-york-yankees', 'sport/baseball/leagues/mlb/teams-you-follow/new-york-yankees', 'New York Yankees', 'team', null, 'sport/baseball/leagues/mlb', 'New York Yankees'),
  ('sport/baseball/leagues/mlb/teams-you-follow/atlanta-braves', 'sport/baseball/leagues/mlb/teams-you-follow/atlanta-braves', 'Atlanta Braves', 'team', null, 'sport/baseball/leagues/mlb', 'Atlanta Braves'),
  ('sport/baseball/leagues/mlb/teams-you-follow/houston-astros', 'sport/baseball/leagues/mlb/teams-you-follow/houston-astros', 'Houston Astros', 'team', null, 'sport/baseball/leagues/mlb', 'Houston Astros'),
  ('sport/baseball/leagues/mlb/teams-you-follow/philadelphia-phillies', 'sport/baseball/leagues/mlb/teams-you-follow/philadelphia-phillies', 'Philadelphia Phillies', 'team', null, 'sport/baseball/leagues/mlb', 'Philadelphia Phillies'),
  ('sport/baseball/leagues/mlb/teams-you-follow/new-york-mets', 'sport/baseball/leagues/mlb/teams-you-follow/new-york-mets', 'New York Mets', 'team', null, 'sport/baseball/leagues/mlb', 'New York Mets'),
  ('sport/baseball/leagues/mlb/people-to-follow/shohei-ohtani', 'sport/baseball/leagues/mlb/people-to-follow/shohei-ohtani', 'Shohei Ohtani', 'person', null, 'sport/baseball/leagues/mlb', 'Shohei Ohtani'),
  ('sport/baseball/leagues/mlb/people-to-follow/aaron-judge', 'sport/baseball/leagues/mlb/people-to-follow/aaron-judge', 'Aaron Judge', 'person', null, 'sport/baseball/leagues/mlb', 'Aaron Judge'),
  ('sport/baseball/leagues/mlb/people-to-follow/mookie-betts', 'sport/baseball/leagues/mlb/people-to-follow/mookie-betts', 'Mookie Betts', 'person', null, 'sport/baseball/leagues/mlb', 'Mookie Betts'),
  ('sport/soccer/leagues-competitions/premier-league', 'sport/soccer/leagues-competitions/premier-league', 'Premier League', 'league', null, 'sport/soccer', 'Premier League'),
  ('sport/soccer/leagues-competitions/premier-league/teams-you-follow/manchester-city', 'sport/soccer/leagues-competitions/premier-league/teams-you-follow/manchester-city', 'Manchester City', 'team', null, 'sport/soccer/leagues-competitions/premier-league', 'Manchester City'),
  ('sport/soccer/leagues-competitions/premier-league/teams-you-follow/arsenal', 'sport/soccer/leagues-competitions/premier-league/teams-you-follow/arsenal', 'Arsenal', 'team', null, 'sport/soccer/leagues-competitions/premier-league', 'Arsenal'),
  ('sport/soccer/leagues-competitions/premier-league/teams-you-follow/liverpool', 'sport/soccer/leagues-competitions/premier-league/teams-you-follow/liverpool', 'Liverpool', 'team', null, 'sport/soccer/leagues-competitions/premier-league', 'Liverpool'),
  ('sport/soccer/leagues-competitions/premier-league/teams-you-follow/manchester-united', 'sport/soccer/leagues-competitions/premier-league/teams-you-follow/manchester-united', 'Manchester United', 'team', null, 'sport/soccer/leagues-competitions/premier-league', 'Manchester United'),
  ('sport/soccer/leagues-competitions/premier-league/teams-you-follow/chelsea', 'sport/soccer/leagues-competitions/premier-league/teams-you-follow/chelsea', 'Chelsea', 'team', null, 'sport/soccer/leagues-competitions/premier-league', 'Chelsea'),
  ('sport/soccer/leagues-competitions/premier-league/teams-you-follow/tottenham', 'sport/soccer/leagues-competitions/premier-league/teams-you-follow/tottenham', 'Tottenham', 'team', null, 'sport/soccer/leagues-competitions/premier-league', 'Tottenham'),
  ('sport/soccer/leagues-competitions/la-liga', 'sport/soccer/leagues-competitions/la-liga', 'La Liga', 'league', null, 'sport/soccer', 'La Liga'),
  ('sport/soccer/leagues-competitions/la-liga/teams-you-follow/real-madrid', 'sport/soccer/leagues-competitions/la-liga/teams-you-follow/real-madrid', 'Real Madrid', 'team', null, 'sport/soccer/leagues-competitions/la-liga', 'Real Madrid'),
  ('sport/soccer/leagues-competitions/la-liga/teams-you-follow/barcelona', 'sport/soccer/leagues-competitions/la-liga/teams-you-follow/barcelona', 'Barcelona', 'team', null, 'sport/soccer/leagues-competitions/la-liga', 'Barcelona'),
  ('sport/soccer/leagues-competitions/la-liga/teams-you-follow/atl-tico-madrid', 'sport/soccer/leagues-competitions/la-liga/teams-you-follow/atl-tico-madrid', 'Atlético Madrid', 'team', null, 'sport/soccer/leagues-competitions/la-liga', 'Atlético Madrid'),
  ('sport/soccer/leagues-competitions/champions-league', 'sport/soccer/leagues-competitions/champions-league', 'Champions League', 'league', null, 'sport/soccer', 'Champions League'),
  ('sport/soccer/people-to-follow/lionel-messi', 'sport/soccer/people-to-follow/lionel-messi', 'Lionel Messi', 'person', null, 'sport/soccer', 'Lionel Messi'),
  ('sport/soccer/people-to-follow/cristiano-ronaldo', 'sport/soccer/people-to-follow/cristiano-ronaldo', 'Cristiano Ronaldo', 'person', null, 'sport/soccer', 'Cristiano Ronaldo'),
  ('sport/soccer/people-to-follow/erling-haaland', 'sport/soccer/people-to-follow/erling-haaland', 'Erling Haaland', 'person', null, 'sport/soccer', 'Erling Haaland'),
  ('sport/soccer/people-to-follow/kylian-mbapp', 'sport/soccer/people-to-follow/kylian-mbapp', 'Kylian Mbappé', 'person', null, 'sport/soccer', 'Kylian Mbappé'),
  ('sport/motorsport/series/formula-1', 'sport/motorsport/series/formula-1', 'Formula 1', 'league', null, 'sport/motorsport', 'Formula 1'),
  ('sport/motorsport/series/formula-1/teams-you-follow/red-bull', 'sport/motorsport/series/formula-1/teams-you-follow/red-bull', 'Red Bull', 'team', null, 'sport/motorsport/series/formula-1', 'Red Bull'),
  ('sport/motorsport/series/formula-1/teams-you-follow/ferrari', 'sport/motorsport/series/formula-1/teams-you-follow/ferrari', 'Ferrari', 'team', null, 'sport/motorsport/series/formula-1', 'Ferrari'),
  ('sport/motorsport/series/formula-1/teams-you-follow/mclaren', 'sport/motorsport/series/formula-1/teams-you-follow/mclaren', 'McLaren', 'team', null, 'sport/motorsport/series/formula-1', 'McLaren'),
  ('sport/motorsport/series/formula-1/teams-you-follow/mercedes', 'sport/motorsport/series/formula-1/teams-you-follow/mercedes', 'Mercedes', 'team', null, 'sport/motorsport/series/formula-1', 'Mercedes'),
  ('sport/motorsport/series/formula-1/teams-you-follow/aston-martin', 'sport/motorsport/series/formula-1/teams-you-follow/aston-martin', 'Aston Martin', 'team', null, 'sport/motorsport/series/formula-1', 'Aston Martin'),
  ('sport/motorsport/series/formula-1/people-to-follow/max-verstappen', 'sport/motorsport/series/formula-1/people-to-follow/max-verstappen', 'Max Verstappen', 'person', null, 'sport/motorsport/series/formula-1', 'Max Verstappen'),
  ('sport/motorsport/series/formula-1/people-to-follow/lando-norris', 'sport/motorsport/series/formula-1/people-to-follow/lando-norris', 'Lando Norris', 'person', null, 'sport/motorsport/series/formula-1', 'Lando Norris'),
  ('sport/motorsport/series/formula-1/people-to-follow/charles-leclerc', 'sport/motorsport/series/formula-1/people-to-follow/charles-leclerc', 'Charles Leclerc', 'person', null, 'sport/motorsport/series/formula-1', 'Charles Leclerc'),
  ('sport/motorsport/series/formula-1/people-to-follow/lewis-hamilton', 'sport/motorsport/series/formula-1/people-to-follow/lewis-hamilton', 'Lewis Hamilton', 'person', null, 'sport/motorsport/series/formula-1', 'Lewis Hamilton'),
  ('sport/tennis/players/carlos-alcaraz', 'sport/tennis/players/carlos-alcaraz', 'Carlos Alcaraz', 'person', null, 'sport/tennis', 'Carlos Alcaraz'),
  ('sport/tennis/players/jannik-sinner', 'sport/tennis/players/jannik-sinner', 'Jannik Sinner', 'person', null, 'sport/tennis', 'Jannik Sinner'),
  ('sport/tennis/players/novak-djokovic', 'sport/tennis/players/novak-djokovic', 'Novak Djokovic', 'person', null, 'sport/tennis', 'Novak Djokovic'),
  ('sport/tennis/players/iga-swiatek', 'sport/tennis/players/iga-swiatek', 'Iga Swiatek', 'person', null, 'sport/tennis', 'Iga Swiatek'),
  ('sport/tennis/players/aryna-sabalenka', 'sport/tennis/players/aryna-sabalenka', 'Aryna Sabalenka', 'person', null, 'sport/tennis', 'Aryna Sabalenka'),
  ('sport/tennis/players/coco-gauff', 'sport/tennis/players/coco-gauff', 'Coco Gauff', 'person', null, 'sport/tennis', 'Coco Gauff'),
  ('sport/cricket/leagues/indian-premier-league-ipl', 'sport/cricket/leagues/indian-premier-league-ipl', 'Indian Premier League (IPL)', 'league', null, 'sport/cricket', 'Indian Premier League (IPL)'),
  ('sport/cricket/leagues/indian-premier-league-ipl/teams-you-follow/mumbai-indians', 'sport/cricket/leagues/indian-premier-league-ipl/teams-you-follow/mumbai-indians', 'Mumbai Indians', 'team', null, 'sport/cricket/leagues/indian-premier-league-ipl', 'Mumbai Indians'),
  ('sport/cricket/leagues/indian-premier-league-ipl/teams-you-follow/chennai-super-kings', 'sport/cricket/leagues/indian-premier-league-ipl/teams-you-follow/chennai-super-kings', 'Chennai Super Kings', 'team', null, 'sport/cricket/leagues/indian-premier-league-ipl', 'Chennai Super Kings'),
  ('sport/cricket/leagues/indian-premier-league-ipl/teams-you-follow/royal-challengers-bengaluru', 'sport/cricket/leagues/indian-premier-league-ipl/teams-you-follow/royal-challengers-bengaluru', 'Royal Challengers Bengaluru', 'team', null, 'sport/cricket/leagues/indian-premier-league-ipl', 'Royal Challengers Bengaluru'),
  ('sport/cricket/leagues/indian-premier-league-ipl/teams-you-follow/kolkata-knight-riders', 'sport/cricket/leagues/indian-premier-league-ipl/teams-you-follow/kolkata-knight-riders', 'Kolkata Knight Riders', 'team', null, 'sport/cricket/leagues/indian-premier-league-ipl', 'Kolkata Knight Riders'),
  ('sport/cricket/leagues/indian-premier-league-ipl/teams-you-follow/gujarat-titans', 'sport/cricket/leagues/indian-premier-league-ipl/teams-you-follow/gujarat-titans', 'Gujarat Titans', 'team', null, 'sport/cricket/leagues/indian-premier-league-ipl', 'Gujarat Titans'),
  ('sport/cricket/people-to-follow/virat-kohli', 'sport/cricket/people-to-follow/virat-kohli', 'Virat Kohli', 'person', null, 'sport/cricket', 'Virat Kohli'),
  ('sport/cricket/people-to-follow/jasprit-bumrah', 'sport/cricket/people-to-follow/jasprit-bumrah', 'Jasprit Bumrah', 'person', null, 'sport/cricket', 'Jasprit Bumrah'),
  ('sport/cricket/people-to-follow/pat-cummins', 'sport/cricket/people-to-follow/pat-cummins', 'Pat Cummins', 'person', null, 'sport/cricket', 'Pat Cummins'),
  ('sport/cricket/people-to-follow/joe-root', 'sport/cricket/people-to-follow/joe-root', 'Joe Root', 'person', null, 'sport/cricket', 'Joe Root')
on conflict (entity_id) do nothing;

-- ── Arts (51) ──────────────────────────────────────────────────────
insert into entities (entity_id, entity_slug, entity_label, entity_kind, entity_ticker, entity_parent_slug, entity_search_query)
values
  ('arts/music/pick-genres-then-artists/pop', 'arts/music/pick-genres-then-artists/pop', 'Pop', 'genre', null, 'arts/music', 'Pop'),
  ('arts/music/pick-genres-then-artists/pop/artists-bands/taylor-swift', 'arts/music/pick-genres-then-artists/pop/artists-bands/taylor-swift', 'Taylor Swift', 'person', null, 'arts/music/pick-genres-then-artists/pop', 'Taylor Swift'),
  ('arts/music/pick-genres-then-artists/pop/artists-bands/billie-eilish', 'arts/music/pick-genres-then-artists/pop/artists-bands/billie-eilish', 'Billie Eilish', 'person', null, 'arts/music/pick-genres-then-artists/pop', 'Billie Eilish'),
  ('arts/music/pick-genres-then-artists/pop/artists-bands/sabrina-carpenter', 'arts/music/pick-genres-then-artists/pop/artists-bands/sabrina-carpenter', 'Sabrina Carpenter', 'person', null, 'arts/music/pick-genres-then-artists/pop', 'Sabrina Carpenter'),
  ('arts/music/pick-genres-then-artists/pop/artists-bands/dua-lipa', 'arts/music/pick-genres-then-artists/pop/artists-bands/dua-lipa', 'Dua Lipa', 'person', null, 'arts/music/pick-genres-then-artists/pop', 'Dua Lipa'),
  ('arts/music/pick-genres-then-artists/pop/artists-bands/ariana-grande', 'arts/music/pick-genres-then-artists/pop/artists-bands/ariana-grande', 'Ariana Grande', 'person', null, 'arts/music/pick-genres-then-artists/pop', 'Ariana Grande'),
  ('arts/music/pick-genres-then-artists/pop/artists-bands/olivia-rodrigo', 'arts/music/pick-genres-then-artists/pop/artists-bands/olivia-rodrigo', 'Olivia Rodrigo', 'person', null, 'arts/music/pick-genres-then-artists/pop', 'Olivia Rodrigo'),
  ('arts/music/pick-genres-then-artists/hip-hop-r-b', 'arts/music/pick-genres-then-artists/hip-hop-r-b', 'Hip-hop & R&B', 'genre', null, 'arts/music', 'Hip-hop & R&B'),
  ('arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/drake', 'arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/drake', 'Drake', 'person', null, 'arts/music/pick-genres-then-artists/hip-hop-r-b', 'Drake'),
  ('arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/kendrick-lamar', 'arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/kendrick-lamar', 'Kendrick Lamar', 'person', null, 'arts/music/pick-genres-then-artists/hip-hop-r-b', 'Kendrick Lamar'),
  ('arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/sza', 'arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/sza', 'SZA', 'person', null, 'arts/music/pick-genres-then-artists/hip-hop-r-b', 'SZA'),
  ('arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/travis-scott', 'arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/travis-scott', 'Travis Scott', 'person', null, 'arts/music/pick-genres-then-artists/hip-hop-r-b', 'Travis Scott'),
  ('arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/doja-cat', 'arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/doja-cat', 'Doja Cat', 'person', null, 'arts/music/pick-genres-then-artists/hip-hop-r-b', 'Doja Cat'),
  ('arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/tyler-the-creator', 'arts/music/pick-genres-then-artists/hip-hop-r-b/artists-bands/tyler-the-creator', 'Tyler, the Creator', 'person', null, 'arts/music/pick-genres-then-artists/hip-hop-r-b', 'Tyler, the Creator'),
  ('arts/music/pick-genres-then-artists/rock-indie', 'arts/music/pick-genres-then-artists/rock-indie', 'Rock & indie', 'genre', null, 'arts/music', 'Rock & indie'),
  ('arts/music/pick-genres-then-artists/rock-indie/artists-bands/coldplay', 'arts/music/pick-genres-then-artists/rock-indie/artists-bands/coldplay', 'Coldplay', 'person', null, 'arts/music/pick-genres-then-artists/rock-indie', 'Coldplay'),
  ('arts/music/pick-genres-then-artists/rock-indie/artists-bands/arctic-monkeys', 'arts/music/pick-genres-then-artists/rock-indie/artists-bands/arctic-monkeys', 'Arctic Monkeys', 'person', null, 'arts/music/pick-genres-then-artists/rock-indie', 'Arctic Monkeys'),
  ('arts/music/pick-genres-then-artists/rock-indie/artists-bands/foo-fighters', 'arts/music/pick-genres-then-artists/rock-indie/artists-bands/foo-fighters', 'Foo Fighters', 'person', null, 'arts/music/pick-genres-then-artists/rock-indie', 'Foo Fighters'),
  ('arts/music/pick-genres-then-artists/rock-indie/artists-bands/the-1975', 'arts/music/pick-genres-then-artists/rock-indie/artists-bands/the-1975', 'The 1975', 'person', null, 'arts/music/pick-genres-then-artists/rock-indie', 'The 1975'),
  ('arts/music/pick-genres-then-artists/rock-indie/artists-bands/hozier', 'arts/music/pick-genres-then-artists/rock-indie/artists-bands/hozier', 'Hozier', 'person', null, 'arts/music/pick-genres-then-artists/rock-indie', 'Hozier'),
  ('arts/music/pick-genres-then-artists/country', 'arts/music/pick-genres-then-artists/country', 'Country', 'genre', null, 'arts/music', 'Country'),
  ('arts/music/pick-genres-then-artists/country/artists-bands/morgan-wallen', 'arts/music/pick-genres-then-artists/country/artists-bands/morgan-wallen', 'Morgan Wallen', 'person', null, 'arts/music/pick-genres-then-artists/country', 'Morgan Wallen'),
  ('arts/music/pick-genres-then-artists/country/artists-bands/zach-bryan', 'arts/music/pick-genres-then-artists/country/artists-bands/zach-bryan', 'Zach Bryan', 'person', null, 'arts/music/pick-genres-then-artists/country', 'Zach Bryan'),
  ('arts/music/pick-genres-then-artists/country/artists-bands/luke-combs', 'arts/music/pick-genres-then-artists/country/artists-bands/luke-combs', 'Luke Combs', 'person', null, 'arts/music/pick-genres-then-artists/country', 'Luke Combs'),
  ('arts/music/pick-genres-then-artists/country/artists-bands/chris-stapleton', 'arts/music/pick-genres-then-artists/country/artists-bands/chris-stapleton', 'Chris Stapleton', 'person', null, 'arts/music/pick-genres-then-artists/country', 'Chris Stapleton'),
  ('arts/music/pick-genres-then-artists/electronic', 'arts/music/pick-genres-then-artists/electronic', 'Electronic', 'genre', null, 'arts/music', 'Electronic'),
  ('arts/music/pick-genres-then-artists/electronic/artists-bands/calvin-harris', 'arts/music/pick-genres-then-artists/electronic/artists-bands/calvin-harris', 'Calvin Harris', 'person', null, 'arts/music/pick-genres-then-artists/electronic', 'Calvin Harris'),
  ('arts/music/pick-genres-then-artists/electronic/artists-bands/fred-again', 'arts/music/pick-genres-then-artists/electronic/artists-bands/fred-again', 'Fred again..', 'person', null, 'arts/music/pick-genres-then-artists/electronic', 'Fred again..'),
  ('arts/music/pick-genres-then-artists/electronic/artists-bands/skrillex', 'arts/music/pick-genres-then-artists/electronic/artists-bands/skrillex', 'Skrillex', 'person', null, 'arts/music/pick-genres-then-artists/electronic', 'Skrillex'),
  ('arts/music/pick-genres-then-artists/electronic/artists-bands/odesza', 'arts/music/pick-genres-then-artists/electronic/artists-bands/odesza', 'ODESZA', 'person', null, 'arts/music/pick-genres-then-artists/electronic', 'ODESZA'),
  ('arts/music/pick-genres-then-artists/latin', 'arts/music/pick-genres-then-artists/latin', 'Latin', 'genre', null, 'arts/music', 'Latin'),
  ('arts/music/pick-genres-then-artists/latin/artists-bands/bad-bunny', 'arts/music/pick-genres-then-artists/latin/artists-bands/bad-bunny', 'Bad Bunny', 'person', null, 'arts/music/pick-genres-then-artists/latin', 'Bad Bunny'),
  ('arts/music/pick-genres-then-artists/latin/artists-bands/karol-g', 'arts/music/pick-genres-then-artists/latin/artists-bands/karol-g', 'Karol G', 'person', null, 'arts/music/pick-genres-then-artists/latin', 'Karol G'),
  ('arts/music/pick-genres-then-artists/latin/artists-bands/peso-pluma', 'arts/music/pick-genres-then-artists/latin/artists-bands/peso-pluma', 'Peso Pluma', 'person', null, 'arts/music/pick-genres-then-artists/latin', 'Peso Pluma'),
  ('arts/music/pick-genres-then-artists/latin/artists-bands/shakira', 'arts/music/pick-genres-then-artists/latin/artists-bands/shakira', 'Shakira', 'person', null, 'arts/music/pick-genres-then-artists/latin', 'Shakira'),
  ('arts/music/pick-genres-then-artists/k-pop', 'arts/music/pick-genres-then-artists/k-pop', 'K-pop', 'genre', null, 'arts/music', 'K-pop'),
  ('arts/music/pick-genres-then-artists/k-pop/artists-bands/bts', 'arts/music/pick-genres-then-artists/k-pop/artists-bands/bts', 'BTS', 'person', null, 'arts/music/pick-genres-then-artists/k-pop', 'BTS'),
  ('arts/music/pick-genres-then-artists/k-pop/artists-bands/blackpink', 'arts/music/pick-genres-then-artists/k-pop/artists-bands/blackpink', 'BLACKPINK', 'person', null, 'arts/music/pick-genres-then-artists/k-pop', 'BLACKPINK'),
  ('arts/music/pick-genres-then-artists/k-pop/artists-bands/stray-kids', 'arts/music/pick-genres-then-artists/k-pop/artists-bands/stray-kids', 'Stray Kids', 'person', null, 'arts/music/pick-genres-then-artists/k-pop', 'Stray Kids'),
  ('arts/music/pick-genres-then-artists/k-pop/artists-bands/newjeans', 'arts/music/pick-genres-then-artists/k-pop/artists-bands/newjeans', 'NewJeans', 'person', null, 'arts/music/pick-genres-then-artists/k-pop', 'NewJeans'),
  ('arts/film-cinema/follow/marvel-dc', 'arts/film-cinema/follow/marvel-dc', 'Marvel / DC', 'franchise', null, 'arts/film-cinema', 'Marvel / DC'),
  ('arts/film-cinema/follow/a24', 'arts/film-cinema/follow/a24', 'A24', 'company', null, 'arts/film-cinema', 'A24'),
  ('arts/film-cinema/follow/oscars-cannes', 'arts/film-cinema/follow/oscars-cannes', 'Oscars & Cannes', 'event', null, 'arts/film-cinema', 'Oscars & Cannes'),
  ('arts/film-cinema/follow/christopher-nolan', 'arts/film-cinema/follow/christopher-nolan', 'Christopher Nolan', 'person', null, 'arts/film-cinema', 'Christopher Nolan'),
  ('arts/tv-streaming/platforms-shows/netflix', 'arts/tv-streaming/platforms-shows/netflix', 'Netflix', 'company', null, 'arts/tv-streaming', 'Netflix'),
  ('arts/tv-streaming/platforms-shows/hbo-max', 'arts/tv-streaming/platforms-shows/hbo-max', 'HBO / Max', 'company', null, 'arts/tv-streaming', 'HBO / Max'),
  ('arts/tv-streaming/platforms-shows/disney', 'arts/tv-streaming/platforms-shows/disney', 'Disney+', 'company', null, 'arts/tv-streaming', 'Disney+'),
  ('arts/tv-streaming/platforms-shows/apple-tv', 'arts/tv-streaming/platforms-shows/apple-tv', 'Apple TV+', 'company', null, 'arts/tv-streaming', 'Apple TV+'),
  ('arts/fashion/houses-topics/gucci', 'arts/fashion/houses-topics/gucci', 'Gucci', 'brand', null, 'arts/fashion', 'Gucci'),
  ('arts/fashion/houses-topics/prada', 'arts/fashion/houses-topics/prada', 'Prada', 'brand', null, 'arts/fashion', 'Prada'),
  ('arts/fashion/houses-topics/fashion-weeks', 'arts/fashion/houses-topics/fashion-weeks', 'Fashion weeks', 'event', null, 'arts/fashion', 'Fashion weeks')
on conflict (entity_id) do nothing;

-- Total seeded: 248 entities.
