-- Seed — interests taxonomy: picker TOPIC leaves (topic-persistence RCA fix, 2026-06-09)
--
-- GENERATED by scripts/e2e/generate-picker-interests-seed.ts — do not hand-edit;
-- re-run the generator if src/lib/pickerSeedTree.ts changes.
--
-- One depth-1 row per selectable TOPIC leaf in PICKER_TREE (79 leaves), so
-- persistPickerFollows' findCanonicalInterest (exact case-insensitive ilike on
-- interest_label / interest_slug) resolves every picker topic selection.
-- interest_label = the EXACT picker label; interest_slug is namespaced under the
-- picker category id. Parents resolve to the EXISTING depth-0 rows from
-- supabase/seed/interests.sql by slug subselect (no hardcoded UUIDs), satisfying
-- ck_interest_depth. Depth-1 rows leave interest_segment_slug NULL, matching the
-- existing depth-1 seed convention.
--
-- IDEMPOTENT: `on conflict (interest_slug) do nothing` — safe to re-run; never
-- modifies the existing 18 Phase 1e rows.

insert into interests (interest_slug, interest_label, depth_level, parent_interest_id, interest_sort_order)
select v.interest_slug, v.interest_label, 1, p.interest_id, v.interest_sort_order
from (values
  ('ai.data-center-buildout', 'Data center buildout', 'tech', 10),
  ('ai.compute-energy-demand', 'Compute energy demand', 'tech', 20),
  ('ai.humanoid-robots', 'Humanoid robots', 'tech', 30),
  ('ai.autonomous-vehicles', 'Autonomous vehicles', 'tech', 40),
  ('ai.drones', 'Drones', 'tech', 50),
  ('ai.eu-ai-act', 'EU AI Act', 'tech', 60),
  ('ai.us-policy', 'US policy', 'tech', 70),
  ('ai.china', 'China', 'tech', 80),
  ('ai.global-governance', 'Global governance', 'tech', 90),
  ('ai.alignment-research', 'Alignment research', 'tech', 100),
  ('ai.interpretability', 'Interpretability', 'tech', 110),
  ('ai.evals-red-teaming', 'Evals & red-teaming', 'tech', 120),
  ('ai.catastrophic-risk', 'Catastrophic risk', 'tech', 130),
  ('geopolitics.russia-sanctions', 'Russia sanctions', 'world', 10),
  ('geopolitics.china-tariffs', 'China tariffs', 'world', 20),
  ('geopolitics.export-controls-chips', 'Export controls (chips)', 'world', 30),
  ('geopolitics.oil-opec', 'Oil & OPEC', 'world', 40),
  ('geopolitics.natural-gas-pipelines', 'Natural gas & pipelines', 'world', 50),
  ('geopolitics.critical-minerals', 'Critical minerals', 'world', 60),
  ('business.mergers-acquisitions', 'Mergers & acquisitions', 'business', 10),
  ('business.leadership-executives', 'Leadership & executives', 'business', 20),
  ('business.ipos', 'IPOs', 'business', 30),
  ('business.metals-mining', 'Metals & mining', 'business', 40),
  ('business.agricultural-commodities', 'Agricultural commodities', 'business', 50),
  ('business.stocks-equities', 'Stocks & equities', 'business', 60),
  ('business.bonds', 'Bonds', 'business', 70),
  ('business.major-indices', 'Major indices', 'business', 80),
  ('business.commodities', 'Commodities', 'business', 90),
  ('business.currencies', 'Currencies', 'business', 100),
  ('business.inflation', 'Inflation', 'business', 110),
  ('business.interest-rates-fed', 'Interest rates & Fed', 'business', 120),
  ('business.jobs', 'Jobs', 'business', 130),
  ('business.gdp-growth', 'GDP & growth', 'business', 140),
  ('business.recession-risk', 'Recession risk', 'business', 150),
  ('business.stablecoins', 'Stablecoins', 'business', 160),
  ('environment.solar', 'Solar', 'climate', 10),
  ('environment.wind', 'Wind', 'climate', 20),
  ('environment.nuclear', 'Nuclear', 'climate', 30),
  ('environment.batteries-storage', 'Batteries & storage', 'climate', 40),
  ('environment.electric-vehicles', 'Electric vehicles', 'climate', 50),
  ('environment.hydrogen', 'Hydrogen', 'climate', 60),
  ('environment.hurricanes', 'Hurricanes', 'climate', 70),
  ('environment.wildfires', 'Wildfires', 'climate', 80),
  ('environment.floods', 'Floods', 'climate', 90),
  ('environment.heatwaves-drought', 'Heatwaves & drought', 'climate', 100),
  ('environment.earthquakes', 'Earthquakes', 'climate', 110),
  ('environment.climate-science', 'Climate science', 'climate', 120),
  ('environment.cop-summits', 'COP summits', 'climate', 130),
  ('environment.emissions-targets', 'Emissions targets', 'climate', 140),
  ('environment.carbon-markets', 'Carbon markets', 'climate', 150),
  ('environment.endangered-species', 'Endangered species', 'climate', 160),
  ('environment.forests-habitats', 'Forests & habitats', 'climate', 170),
  ('environment.oceans-coral', 'Oceans & coral', 'climate', 180),
  ('politics.national-elections', 'National elections', 'world', 10),
  ('politics.legislative-races', 'Legislative races', 'world', 20),
  ('politics.state-local', 'State & local', 'world', 30),
  ('politics.campaigns', 'Campaigns', 'world', 40),
  ('politics.immigration', 'Immigration', 'world', 50),
  ('politics.healthcare', 'Healthcare', 'world', 60),
  ('politics.taxes', 'Taxes', 'world', 70),
  ('politics.education', 'Education', 'world', 80),
  ('politics.guns', 'Guns', 'world', 90),
  ('politics.supreme-court', 'Supreme Court', 'world', 100),
  ('politics.major-rulings', 'Major rulings', 'world', 110),
  ('politics.executive-branch', 'Executive branch', 'world', 120),
  ('politics.legislation-bills', 'Legislation & bills', 'world', 130),
  ('politics.budget', 'Budget', 'world', 140),
  ('tech.launches-missions', 'Launches & missions', 'tech', 10),
  ('tech.consoles', 'Consoles', 'tech', 20),
  ('tech.pc-gaming', 'PC gaming', 'tech', 30),
  ('tech.esports', 'Esports', 'tech', 40),
  ('tech.data-breaches', 'Data breaches', 'tech', 50),
  ('tech.ransomware', 'Ransomware', 'tech', 60),
  ('tech.vulnerabilities', 'Vulnerabilities', 'tech', 70),
  ('arts.box-office', 'Box office', 'entertainment', 10),
  ('arts.fiction', 'Fiction', 'entertainment', 20),
  ('arts.nonfiction', 'Nonfiction', 'entertainment', 30),
  ('arts.prizes-bestsellers', 'Prizes & bestsellers', 'entertainment', 40),
  ('arts.trends', 'Trends', 'entertainment', 50)
) as v (interest_slug, interest_label, parent_slug, interest_sort_order)
join interests p on p.interest_slug = v.parent_slug
on conflict (interest_slug) do nothing;
