-- Seed — static outlet → bias lookup table (phase-2c SP1; reference/supabase-schema.md §2 `outlets`)
--
-- Source of truth for every Coverage-tab number: GDELT returns DOMAINS, this maps
-- domain → AllSides/Ad Fontes L/C/R lean. Master-plan Decision #6 — a one-time static
-- table, not a per-story API call.
--
-- Depends on migration 0004 (adds outlets.outlet_domain + its unique index). Run after migrations.
-- IDEMPOTENT: `on conflict (outlet_name) do nothing` — safe to re-run.
--
-- Lean mapping: AllSides 5-point collapsed to the 3-value bias_lean enum —
--   Left + Lean Left → 'left'; Center/Mixed → 'center'; Lean Right + Right → 'right'.
--   Topical/non-political outlets (sport, most tech/science, entertainment) → 'center'.

insert into outlets (outlet_name, outlet_bias_lean, outlet_domain)
values
  -- ── US national news — TV / wire / network ────────────────────────────────
  ('CNN', 'left', 'cnn.com'),
  ('Fox News', 'right', 'foxnews.com'),
  ('MSNBC', 'left', 'msnbc.com'),
  ('NBC News', 'left', 'nbcnews.com'),
  ('ABC News', 'left', 'abcnews.go.com'),
  ('CBS News', 'left', 'cbsnews.com'),
  ('The Associated Press', 'center', 'apnews.com'),
  ('Reuters', 'center', 'reuters.com'),
  ('NPR', 'left', 'npr.org'),
  ('PBS NewsHour', 'center', 'pbs.org'),
  ('Newsmax', 'right', 'newsmax.com'),
  ('One America News Network', 'right', 'oann.com'),
  ('NewsNation', 'center', 'newsnationnow.com'),
  ('C-SPAN', 'center', 'c-span.org'),
  ('Voice of America', 'center', 'voanews.com'),
  -- ── US national news — newspapers / digital ───────────────────────────────
  ('The New York Times', 'left', 'nytimes.com'),
  ('The Washington Post', 'left', 'washingtonpost.com'),
  ('The Wall Street Journal', 'center', 'wsj.com'),
  ('USA Today', 'center', 'usatoday.com'),
  ('Los Angeles Times', 'left', 'latimes.com'),
  ('The Boston Globe', 'left', 'bostonglobe.com'),
  ('Chicago Tribune', 'center', 'chicagotribune.com'),
  ('The Hill', 'center', 'thehill.com'),
  ('Politico', 'center', 'politico.com'),
  ('Axios', 'center', 'axios.com'),
  ('Bloomberg', 'center', 'bloomberg.com'),
  ('The Atlantic', 'left', 'theatlantic.com'),
  ('The New Yorker', 'left', 'newyorker.com'),
  ('Vox', 'left', 'vox.com'),
  ('Slate', 'left', 'slate.com'),
  ('Mother Jones', 'left', 'motherjones.com'),
  ('The Nation', 'left', 'thenation.com'),
  ('The Intercept', 'left', 'theintercept.com'),
  ('HuffPost', 'left', 'huffpost.com'),
  ('BuzzFeed News', 'left', 'buzzfeednews.com'),
  ('Salon', 'left', 'salon.com'),
  ('The Daily Beast', 'left', 'thedailybeast.com'),
  ('ProPublica', 'left', 'propublica.org'),
  ('Time', 'left', 'time.com'),
  ('Newsweek', 'center', 'newsweek.com'),
  ('Forbes', 'center', 'forbes.com'),
  ('Fortune', 'center', 'fortune.com'),
  ('The Christian Science Monitor', 'center', 'csmonitor.com'),
  ('RealClearPolitics', 'right', 'realclearpolitics.com'),
  ('National Review', 'right', 'nationalreview.com'),
  ('New York Post', 'right', 'nypost.com'),
  ('The Washington Times', 'right', 'washingtontimes.com'),
  ('The Washington Examiner', 'right', 'washingtonexaminer.com'),
  ('The Daily Wire', 'right', 'dailywire.com'),
  ('The Federalist', 'right', 'thefederalist.com'),
  ('Breitbart', 'right', 'breitbart.com'),
  ('The Daily Caller', 'right', 'dailycaller.com'),
  ('The Blaze', 'right', 'theblaze.com'),
  ('The American Conservative', 'right', 'theamericanconservative.com'),
  ('Reason', 'right', 'reason.com'),
  ('The Epoch Times', 'right', 'theepochtimes.com'),
  ('The Free Press', 'center', 'thefp.com'),
  ('Semafor', 'center', 'semafor.com'),
  ('The Dispatch', 'right', 'thedispatch.com'),
  ('Daily Mail', 'right', 'dailymail.co.uk'),
  -- ── Major English-language international outlets ───────────────────────────
  ('BBC News', 'center', 'bbc.com'),
  ('The Guardian', 'left', 'theguardian.com'),
  ('The Economist', 'center', 'economist.com'),
  ('Financial Times', 'center', 'ft.com'),
  ('Al Jazeera', 'center', 'aljazeera.com'),
  ('The Independent', 'left', 'independent.co.uk'),
  ('The Telegraph', 'right', 'telegraph.co.uk'),
  ('The Times', 'center', 'thetimes.co.uk'),
  ('Sky News', 'center', 'news.sky.com'),
  ('Agence France-Presse', 'center', 'afp.com'),
  ('Deutsche Welle', 'center', 'dw.com'),
  ('France 24', 'center', 'france24.com'),
  ('Euronews', 'center', 'euronews.com'),
  ('The Globe and Mail', 'center', 'theglobeandmail.com'),
  ('CBC News', 'center', 'cbc.ca'),
  ('CTV News', 'center', 'ctvnews.ca'),
  ('National Post', 'right', 'nationalpost.com'),
  ('Toronto Star', 'left', 'thestar.com'),
  ('The Sydney Morning Herald', 'center', 'smh.com.au'),
  ('ABC News Australia', 'center', 'abc.net.au'),
  ('The Australian', 'right', 'theaustralian.com.au'),
  ('The Irish Times', 'center', 'irishtimes.com'),
  ('The Hindu', 'center', 'thehindu.com'),
  ('The Times of India', 'center', 'timesofindia.indiatimes.com'),
  ('Hindustan Times', 'center', 'hindustantimes.com'),
  ('NDTV', 'center', 'ndtv.com'),
  ('The Indian Express', 'center', 'indianexpress.com'),
  ('The Japan Times', 'center', 'japantimes.co.jp'),
  ('The Straits Times', 'center', 'straitstimes.com'),
  ('South China Morning Post', 'center', 'scmp.com'),
  ('The Moscow Times', 'center', 'themoscowtimes.com'),
  ('The Jerusalem Post', 'center', 'jpost.com'),
  ('Haaretz', 'left', 'haaretz.com'),
  ('The Times of Israel', 'center', 'timesofisrael.com'),
  ('Kyiv Independent', 'center', 'kyivindependent.com'),
  -- ── Politics / fact-check / opinion ───────────────────────────────────────
  ('PolitiFact', 'left', 'politifact.com'),
  ('FactCheck.org', 'center', 'factcheck.org'),
  ('Snopes', 'center', 'snopes.com'),
  ('Roll Call', 'center', 'rollcall.com'),
  ('The Bulwark', 'center', 'thebulwark.com'),
  ('Jacobin', 'left', 'jacobin.com'),
  ('The American Prospect', 'left', 'prospect.org'),
  ('The New Republic', 'left', 'newrepublic.com'),
  -- ── Business / markets / finance ──────────────────────────────────────────
  ('CNBC', 'center', 'cnbc.com'),
  ('MarketWatch', 'center', 'marketwatch.com'),
  ('Business Insider', 'left', 'businessinsider.com'),
  ('Barron''s', 'center', 'barrons.com'),
  ('Investor''s Business Daily', 'center', 'investors.com'),
  ('The Motley Fool', 'center', 'fool.com'),
  ('Seeking Alpha', 'center', 'seekingalpha.com'),
  ('Yahoo Finance', 'center', 'finance.yahoo.com'),
  ('Investopedia', 'center', 'investopedia.com'),
  ('Kiplinger', 'center', 'kiplinger.com'),
  ('Morningstar', 'center', 'morningstar.com'),
  ('Quartz', 'center', 'qz.com'),
  ('Fast Company', 'center', 'fastcompany.com'),
  ('Inc.', 'center', 'inc.com'),
  ('Entrepreneur', 'center', 'entrepreneur.com'),
  ('Harvard Business Review', 'center', 'hbr.org'),
  ('Nikkei Asia', 'center', 'asia.nikkei.com'),
  ('TheStreet', 'center', 'thestreet.com'),
  ('Benzinga', 'center', 'benzinga.com'),
  -- ── Tech ──────────────────────────────────────────────────────────────────
  ('The Verge', 'center', 'theverge.com'),
  ('TechCrunch', 'center', 'techcrunch.com'),
  ('Ars Technica', 'center', 'arstechnica.com'),
  ('Wired', 'left', 'wired.com'),
  ('Engadget', 'center', 'engadget.com'),
  ('Gizmodo', 'left', 'gizmodo.com'),
  ('CNET', 'center', 'cnet.com'),
  ('Mashable', 'center', 'mashable.com'),
  ('ZDNET', 'center', 'zdnet.com'),
  ('TechRadar', 'center', 'techradar.com'),
  ('Tom''s Hardware', 'center', 'tomshardware.com'),
  ('The Register', 'center', 'theregister.com'),
  ('VentureBeat', 'center', 'venturebeat.com'),
  ('The Information', 'center', 'theinformation.com'),
  ('9to5Mac', 'center', '9to5mac.com'),
  ('MacRumors', 'center', 'macrumors.com'),
  ('Android Police', 'center', 'androidpolice.com'),
  ('Digital Trends', 'center', 'digitaltrends.com'),
  ('IEEE Spectrum', 'center', 'spectrum.ieee.org'),
  ('MIT Technology Review', 'center', 'technologyreview.com'),
  ('Rest of World', 'center', 'restofworld.org'),
  ('404 Media', 'center', '404media.co'),
  ('Bleeping Computer', 'center', 'bleepingcomputer.com'),
  ('Krebs on Security', 'center', 'krebsonsecurity.com'),
  -- ── Science ───────────────────────────────────────────────────────────────
  ('Nature', 'center', 'nature.com'),
  ('Science', 'center', 'science.org'),
  ('Scientific American', 'center', 'scientificamerican.com'),
  ('New Scientist', 'center', 'newscientist.com'),
  ('Live Science', 'center', 'livescience.com'),
  ('Phys.org', 'center', 'phys.org'),
  ('ScienceDaily', 'center', 'sciencedaily.com'),
  ('Quanta Magazine', 'center', 'quantamagazine.org'),
  ('Space.com', 'center', 'space.com'),
  ('Sky & Telescope', 'center', 'skyandtelescope.org'),
  ('NASA', 'center', 'nasa.gov'),
  ('National Geographic', 'center', 'nationalgeographic.com'),
  ('Smithsonian Magazine', 'center', 'smithsonianmag.com'),
  ('Popular Science', 'center', 'popsci.com'),
  ('Popular Mechanics', 'center', 'popularmechanics.com'),
  ('EurekAlert!', 'center', 'eurekalert.org'),
  -- ── Climate / environment ─────────────────────────────────────────────────
  ('Inside Climate News', 'center', 'insideclimatenews.org'),
  ('Grist', 'left', 'grist.org'),
  ('Carbon Brief', 'center', 'carbonbrief.org'),
  ('E&E News', 'center', 'eenews.net'),
  ('Mongabay', 'center', 'mongabay.com'),
  ('Yale Environment 360', 'center', 'e360.yale.edu'),
  ('Climate Home News', 'center', 'climatechangenews.com'),
  -- ── Health / medicine ─────────────────────────────────────────────────────
  ('STAT News', 'center', 'statnews.com'),
  ('Kaiser Health News', 'center', 'kffhealthnews.org'),
  ('MedPage Today', 'center', 'medpagetoday.com'),
  ('Healthline', 'center', 'healthline.com'),
  ('WebMD', 'center', 'webmd.com'),
  ('Medical News Today', 'center', 'medicalnewstoday.com'),
  ('The Lancet', 'center', 'thelancet.com'),
  ('The BMJ', 'center', 'bmj.com'),
  ('Endpoints News', 'center', 'endpts.com'),
  ('Fierce Pharma', 'center', 'fiercepharma.com'),
  -- ── Sport ─────────────────────────────────────────────────────────────────
  ('ESPN', 'center', 'espn.com'),
  ('The Athletic', 'center', 'theathletic.com'),
  ('Sky Sports', 'center', 'skysports.com'),
  ('Bleacher Report', 'center', 'bleacherreport.com'),
  ('CBS Sports', 'center', 'cbssports.com'),
  ('Yahoo Sports', 'center', 'sports.yahoo.com'),
  ('Sports Illustrated', 'center', 'si.com'),
  ('Fox Sports', 'center', 'foxsports.com'),
  ('NBC Sports', 'center', 'nbcsports.com'),
  ('The Sporting News', 'center', 'sportingnews.com'),
  ('ESPN Cricinfo', 'center', 'espncricinfo.com'),
  ('Goal', 'center', 'goal.com'),
  ('SB Nation', 'center', 'sbnation.com'),
  ('The Ringer', 'center', 'theringer.com'),
  ('Autosport', 'center', 'autosport.com'),
  ('Cycling News', 'center', 'cyclingnews.com'),
  ('Marca', 'center', 'marca.com'),
  ('L''Équipe', 'center', 'lequipe.fr'),
  -- ── Entertainment / culture / lifestyle ───────────────────────────────────
  ('Variety', 'center', 'variety.com'),
  ('The Hollywood Reporter', 'center', 'hollywoodreporter.com'),
  ('Deadline', 'center', 'deadline.com'),
  ('Entertainment Weekly', 'center', 'ew.com'),
  ('Rolling Stone', 'left', 'rollingstone.com'),
  ('Pitchfork', 'center', 'pitchfork.com'),
  ('Billboard', 'center', 'billboard.com'),
  ('IGN', 'center', 'ign.com'),
  ('Polygon', 'center', 'polygon.com'),
  ('Kotaku', 'center', 'kotaku.com'),
  ('Eurogamer', 'center', 'eurogamer.net'),
  ('TMZ', 'center', 'tmz.com'),
  ('People', 'center', 'people.com'),
  ('Vulture', 'left', 'vulture.com'),
  ('Vanity Fair', 'left', 'vanityfair.com'),
  ('GQ', 'center', 'gq.com'),
  ('Vogue', 'center', 'vogue.com'),
  ('Condé Nast Traveler', 'center', 'cntraveler.com'),
  ('Architectural Digest', 'center', 'architecturaldigest.com'),
  ('Bon Appétit', 'center', 'bonappetit.com'),
  -- ── Crypto / Web3 ─────────────────────────────────────────────────────────
  ('CoinDesk', 'center', 'coindesk.com'),
  ('The Block', 'center', 'theblock.co'),
  ('Cointelegraph', 'center', 'cointelegraph.com'),
  ('Decrypt', 'center', 'decrypt.co'),
  ('Blockworks', 'center', 'blockworks.co'),
  ('CryptoSlate', 'center', 'cryptoslate.com'),
  ('Bitcoin Magazine', 'center', 'bitcoinmagazine.com'),
  ('DL News', 'center', 'dlnews.com'),
  ('Protos', 'center', 'protos.com'),
  ('CoinGecko', 'center', 'coingecko.com'),
  -- ── Regional US / additional national ─────────────────────────────────────
  ('The Seattle Times', 'center', 'seattletimes.com'),
  ('San Francisco Chronicle', 'left', 'sfchronicle.com'),
  ('The Dallas Morning News', 'center', 'dallasnews.com'),
  ('The Denver Post', 'center', 'denverpost.com'),
  ('Star Tribune', 'center', 'startribune.com'),
  ('The Philadelphia Inquirer', 'center', 'inquirer.com'),
  ('The Atlanta Journal-Constitution', 'center', 'ajc.com'),
  ('Miami Herald', 'center', 'miamiherald.com'),
  ('The Texas Tribune', 'center', 'texastribune.org'),
  ('The Mercury News', 'center', 'mercurynews.com'),
  ('Tampa Bay Times', 'center', 'tampabay.com'),
  ('Houston Chronicle', 'center', 'houstonchronicle.com'),
  ('The Sacramento Bee', 'center', 'sacbee.com')
on conflict (outlet_name) do nothing;
